defaults: &defaults
  NAME: fogcloud
  # 默认域名
  HOST: 0.0.0.0
  # http-api监听端口
  PORT: 4000
  # 日志级别：debug, info, warn, error, fatal
  LOG_LEVEL: debug
  # gin运行模式：debug, test, release；生产环境请使用release；
  GINMODE: debug
  ENABLE_TLS: true
  # 是否启用不安全的oss下载；true：使用http下载，false：使用https下载；
  INSECURE_OSS: true

  # geo文件路径
  GEO_DATABASE_FILEPATH: /etc/fogcloud/IP2LOCATION-LITE-DB3.BIN
  # 设备地理位置级别：region, country
  GEO_LOCATION_LEVEL: region
  # topics定义文件路径
  THING_TOPICS_FILEPATH: /etc/fogcloud/topics.yaml
  # 部分接口ip白名单，仅白名单内的ip可以访问，这些接口包括：用户注册()，
  IP_WHITE_TABLE: []
  # 用于加密的key值，生产环境请使用长度超过16字节的随机字符串
  AUTH_KEY: "not-a-secure-key"

  # 是否开启云网关
  ENABLE_CLOUD_GATEWAY: true
  # 是否打开遥测
  ENABLE_TELEMETRY: true

  # 管理后台初始账号和密码
  APP_ID: root
  APP_SECRET: fogcloud

  # 系统api错误提示国际化文件路径
  I18N_FILEPATH:
    ZH: /etc/fogcloud/active.zh.json
    EN: /etc/fogcloud/active.en.json

  # redis配置
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  REDIS_PASSWORD:

  # cron定时调度器配置
  CRON_WORKER_MACHINE_ID: 1
  CRON_WORKER_ETCD_ENDPOINTS: 127.0.0.1:2379
  CRON_WORKER_DEFAULT_QUEUE: fogcron
  CRON_WORKER_BROKER_ENDPOINTS: redis://localhost:6379/1
  CRON_WORKER_RESULT_BACKEND_ENDPOINT: redis://localhost:6379/2
  CRON_WORKER_CONCURRENCY: 10
  CRON_WORKER_RESULT_EXPIRE: 10

  # postgres配置
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: fogcloud
  POSTGRES_DBNAME: fogcloud
  POSTGRES_SSLMODE: disable

  # mongo配置
  MONGO_URI: mongodb://127.0.0.1:27017
  MONGO_DBNAME: fogcloud

  # mqtt相关配置
  # mqtt服务器类型：emqx, vernemq, hmq
  MQTT_BROKER_TYPE: emqx
  MQTT_BROKER_ADAPTOR:
    emqx:
      HTTP_AUTH_PATH: /mqtt/auth/emqx
      HTTP_ACL_PATH: /mqtt/acl/emqx
      HTTP_WEBHOOK_PATH: /mqtt/webhook/emqx
    verne:
      HTTP_AUTH_PATH: /mqtt/auth/verne
      HTTP_ACL_PATH: /mqtt/acl/verne
      HTTP_WEBHOOK_PATH: /mqtt/webhook/verne
    hmq:
      AMQP_QUEUE_NAME: fogcloud
      AMQP_EXCHANGE: mqtt.bridge
      HTTP_AUTH_PATH: /mqtt/auth/hmq
      HTTP_ACL_PATH: /mqtt/acl/hmq
  # mqtt服务器域名
  MQTT_BROKER_HOST: 127.0.0.1
  # mqtt服务器mqtt super账号信息
  MQTT_BROKER_ID: admin
  MQTT_BROKER_SECRET: public
  # mqtt服务器管理后台身份信息
  MQTT_DASHBOARD_USERNAME: admin
  MQTT_DASHBOARD_PASSWORD: public
  # mqtt服务对应端口
  MQTT_BROKER_API_PORT: 8081
  MQTT_BROKER_TCP_PORT: 1883
  MQTT_BROKER_TLS_PORT: 8883
  MQTT_BROKER_WS_PORT: 8083
  MQTT_BROKER_WSS_PORT: 8084
  # mqtt连接池大小
  MQTT_CLIENT_POOL_SIZE: 5

  # rabbitmq配置
  RABBITMQ_TLS: false
  RABBITMQ_HOST: 127.0.0.1
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: rabbitmq
  RABBITMQ_PASSWORD: fogcloud
  RABBITMQ_EVENTS_EX: fogcloud.event_notify
  RABBITMQ_QUEUE_MAX_LENGTH: 100

  # minio配置
  MINIO_HOST: 127.0.0.1
  MINIO_API_PORT: 9000
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: fogcloud
  MINIO_ACCESS_KEY: 1234567890
  MINIO_SECRET_KEY: abcdefghi
  MINIO_REGION_NAME: cn-south-1
  MINIO_BUCKET_FIRMWARE: fogcloud-firmware
  MINIO_BUCKET_THING_FILE: fogcloud-thing-file

  # 云函数编译服务配置
  FAAS_ENDPOINT: http://127.0.0.1:8080
  FAAS_USER: admin
  FAAS_PASSWORD: PRhg3ID9iBeG
  FAAS_STORE_ENDPOINT: http://192.168.2.135:3000
  FAAS_BUILDER_ENDPOINT: http://127.0.0.1:8090

  # oauth2回调地址配置
  OAUTH2:
    GITHUB_AUTH_CALLBACK: /#/oauth2/github
    DINGTALK_AGENTID: 1635081269
    DINGTALK_AUTH_CALLBACK: /#/oauth2/dingtalk
    FEISHU_AUTH_CALLBACK: /#/oauth2/feishu

development: &development
  <<: *defaults
  NAME: fogcloud_development

  CRON_WORKER_ETCD_ENDPOINTS: etcd1:2379
  CRON_WORKER_BROKER_ENDPOINTS: redis://redis:6379/1
  CRON_WORKER_RESULT_BACKEND_ENDPOINT: redis://redis:6379/2

  MQTT_BROKER_HOST: mqtt-broker

  REDIS_HOST: redis
  POSTGRES_HOST: postgres
  MONGO_URI: mongodb://mongo:27017
  EMQ_HOST: mqtt-broker
  MINIO_HOST: minio
  RABBITMQ_HOST: rabbitmq
  FAAS_STORE_ENDPOINT: https://fogcloud.io
  FAAS_BUILDER_ENDPOINT: http://faasbuilder:8090
  FAAS_ENDPOINT: http://gateway.openfaas.svc.cluster.local:8080

test:
  <<: *development
  NAME: fogcloud_test
  HOST: demo.beta.fogcloud.io

production:
  <<: *development
  NAME: fogcloud
  HOST: app.fogcloud.io
  FAAS_STORE_ENDPOINT: https://fogcloud.io
