version: "3"

networks:
  fogcloud_net:

volumes:
  fog_postgres_data:
    external: false
  fog_redis_data:
    external: false
  fog_emq_data:
    external: false
  fog_minio_data:
    external: false
  fog_mongo_data:
    external: false
  fog_etcd_data:
    external: false

services:
  fogcloud:
    image: registry.cn-shanghai.aliyuncs.com/fogcloud/fogcloud:beta
    container_name: fogcloud
    restart: unless-stopped
    ports:
      - 4000:4000
      - 4001:15000
    networks:
      - fogcloud_net
    volumes:
      - ./fogcloud.example.yaml:/etc/fogcloud/fogcloud.yaml
    depends_on:
      - redis
      - postgres
      - emqx
      - rabbitmq
      - minio
      - etcd
      - mongo
    command:
      ["fogcloud", "-c", "/etc/fogcloud/fogcloud.yaml", "-e", "development"]

  fogcloud_web:
    image: registry.cn-shanghai.aliyuncs.com/fogcloud/fogcloud_web:beta
    environment:
      API_BASE_URL: http://localhost:4000/api/v1
      MQTT_BASE_URL: ws://localhost:8083/mqtt
    container_name: fog-web
    ports:
      - 8000:8000

  redis:
    image: redis:6.2
    container_name: fog-redis
    restart: unless-stopped
    # ports:
    #   - 6379:6379
    volumes:
      - fog_redis_data:/data
    networks:
      - fogcloud_net

  etcd:
    container_name: fog-etcd
    image: bitnami/etcd:3.5.1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://fog-etcd:2379
    networks:
      - fogcloud_net
    # ports:
    #   - 2379:2379
    #   - 2380:2380
    volumes:
      - fog_etcd_data:/bitnami/etcd/data

  postgres:
    image: postgres:13
    container_name: fog-postgres
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - fog_postgres_data:/var/lib/postgresql/data
    networks:
      - fogcloud_net
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "fogcloud"
      POSTGRES_DB: "fogcloud"

  mongo:
    image: mongo:4.4-rc-focal
    container_name: fog-mongo
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - fog_mongo_data:/data/db
    networks:
      - fogcloud_net      

  emqx:
    image: emqx/emqx:4.2.8
    container_name: fog-emqx
    restart: unless-stopped
    networks:
      - fogcloud_net
    volumes:
      - ./emqx/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf
      - ./emqx/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./emqx/loaded_plugins:/opt/emqx/data/loaded_plugins
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 18083:18083
      - 8883:8883

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: fog-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    networks:
      - fogcloud_net
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  minio:
    image: minio/minio
    container_name: fog-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: fogcloud
      MINIO_ACCESS_KEY: 1234567890
      MINIO_SECRET_KEY: abcdefghi
      MINIO_REGION_NAME: cn-south-1
    volumes:
      - fog_minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - fogcloud_net
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
 